name: crafted_manager
description: Crafted Manager App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  postgres: ^2.6.1
  isolate_bloc: ^2.1.1
  shared_preferences: ^2.1.0
  path_provider: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
