name: crafted_manager
description: Crafted Manager App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  postgres: ^2.6.1
  isolate_bloc: ^2.1.1
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  intl: ^0.18.0
  flutter_local_notifications: ^14.0.0+2
  flutter_local_notifications_platform_interface: ^7.0.0+1
  multi_image_picker: ^4.8.1
  image_picker: ^0.8.4
  pull_to_refresh: ^2.0.0
  flutter_zoom_drawer: ^3.0.4+1
  get:
  flutter_slider_drawer: ^2.1.3
  expansion_tile_card: ^3.0.0
  flutter_native_timezone:
  timezone:
  contacts_service:
  permission_handler: ^8.2.2
  woosignal: ^3.5.0
  onesignal_flutter: ^3.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
